/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/plants/new`; params?: Router.UnknownInputParams; } | { pathname: `/plants/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plants/[id]/diary`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plants/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plants/[id]/measurements`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/plants/new`; params?: Router.UnknownOutputParams; } | { pathname: `/plants/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/plants/[id]/diary`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/plants/[id]/edit`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/plants/[id]/measurements`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/plants/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/plants/new`; params?: Router.UnknownInputParams; } | `/plants/${Router.SingleRoutePart<T>}` | `/plants/${Router.SingleRoutePart<T>}/diary` | `/plants/${Router.SingleRoutePart<T>}/edit` | `/plants/${Router.SingleRoutePart<T>}/measurements` | { pathname: `/plants/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plants/[id]/diary`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plants/[id]/edit`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/plants/[id]/measurements`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
