export { default as Home } from './Home'
export { default as NewPlant } from './NewPlant'
export { default as PlantDetail } from './PlantDetail'
export { default as Calendar } from './Calendar'
export { default as Settings } from './Settings'
